version: '3'

services:
  tom-dev:
    image: moduo/devops:tom-2
    ports:
    - 8080
    labels:
    - "traefik.frontend.rule=Host:tom.dev.tomoud.nl"
  wendy-dev:
    image: moduo/devops:wendy-7
    ports:
    - 8080
    labels:
    - "traefik.frontend.rule=Host:wendy.dev.tomoud.nl"