version: '3'

services:
  tom-dev:
    image: moduo/devops:tom-1
    ports:
    - 8080
    labels:
    - "traefik.frontend.rule=Host:tom.dev.tomoud.nl"
  melvin-dev:
    image: moduo/devops:melvin-6
    ports:
      - 8080
    labels:
      - "traefik.frontend.rule=Host:melvin.dev.tomoud.nl"
