version: '3'

services:
  tom-dev:
    image: moduo/devops:tom-1
    ports:
      - 8080
    labels:
    - "traefik.frontend.rule=Host:tom.dev.tomoud.nl"
  melvin-dev:
    image: moduo/devops:melvin-6
    ports:
      - 8080
    labels:
      - "traefik.frontend.rule=Host:melvin.dev.tomoud.nl"
  dennis-dev:
    image: moduo/devops:dennis-7
    ports:
      - 8080
    labels:
      - "traefik.frontend.rule=Host:dennis.dev.tomoud.nl"
  anne-jan-dev:
    image: moduo/devops:annejan-3
    ports:
      - 8080
    labels:
      - "traefik.frontend.rule=Host:anne-jan.dev.tomoud.nl"