version: '3.3'

services:
  matthijs-dev:
    image: moduo/devops:matthijs-2
    networks:
    - default
    - traefik-net
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      labels:
        - "traefik.port=8080"
        - "traefik.docker.network=traefik-net"
        - "traefik.frontend.rule=Host:matthijs.dev.tomoud.nl"
networks:
  traefik-net:
    external: true